version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - "880:80"
      - "8443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - mysql
      - apache
    networks:
      - wp-network

  apache:
    build:
      dockerfile: ./php-dockerfile
    container_name: apache
    volumes:
      - ./apache/html/domain.com:/var/www/html
      - ./apache/domain.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql
    networks:
      - wp-network

  mysql:
    image: mysql:8.2.0
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: R00tPass
      MYSQL_DATABASE: domain
      MYSQL_USER: domainuser
      MYSQL_PASSWORD: UserPass
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge
